name: "Docs Generator"

on:
    #schedule:
    #    -   cron: 0 0 * * *

    push:
        branches: [ main1 ]

    release:
        types:
            - released

jobs:
    fix:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   name: Setup Node.js
                uses: actions/setup-node@v3.3.0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json
                    coverage: none

            -   name: Cache dependencies
                uses: actions/cache@v3
                id: npm-cache
                with:
                    path: |
                        **/node_modules
                    key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-npm-

            -   name: Install dependencies
                run: |
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction --ansi
                    npm i

            -   name: Download repositories
                run: php bin/docs download TheDragonCode --ansi

            -   name: Compile docs
                run: php bin/docs compile --ansi

            -   name: Build VuePress site
                run: npm run build
                env:
                    VITE_APP_ALGOLIA_APP_ID: ${{ secrets.VITE_APP_ALGOLIA_APP_ID }}
                    VITE_APP_ALGOLIA_API_KEY: ${{ secrets.VITE_APP_ALGOLIA_API_KEY }}
                    VITE_APP_ALGOLIA_INDEX_NAME: ${{ secrets.VITE_APP_ALGOLIA_INDEX_NAME }}

            -   name: Deploy to GitHub Pages
                uses: crazy-max/ghaction-github-pages@v3.0.0
                with:
                    target_branch: gh-pages
                    build_dir: temp/docs/.vuepress/dist
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
